#!/bin/bash

# Gets temperature of the CPU
# Dependencies: lm_sensors

PREFIX=' '
FIRE=' '

CRITICAL_LEVEL=85
WARNING_LEVEL=75


get_cputemp()
{
	# CPU_T=$(cat /sys/devices/platform/coretemp.0/hwmon/hwmon?/temp2_input)
	# CPU_TEMP=$(expr $CPU_T / 1000)

	CPU_TEMP="$(sensors | grep Package | awk 'NR==1{gsub("+", " "); gsub("\\..", " "); print $4}')"

	if [ "$CPU_TEMP" -ge $CRITICAL_LEVEL ]; then
		PREFIX="\x04$FIRE$PREFIX"
    elif [ "$CPU_TEMP" -ge $WARNING_LEVEL ]; then
		PREFIX="\x05$FIRE$PREFIX"
	fi

	echo -e "$PREFIX$CPU_TEMP°C \x01"
}

get_cputemp
