#!/bin/bash

# Prints out the current down network traffic in MB

PREFIX=' '

get_down_traffic()
{
    RECEIVE1=0
    RECEIVE2=0

    IFACES=$(ip -o link show | awk -F': ' '{print $2}')
    for IFACE in $IFACES; do
        if [ $IFACE != "lo" ]; then
            RECEIVE1=$(($(ip -s -c link show $IFACE | tail -n3 | head -n 1 | awk '{printf $1}') + $RECEIVE1))
        fi
    done
    
    sleep 1

    IFACES=$(ip -o link show | awk -F': ' '{print $2}')
    for IFACE in $IFACES; do
        if [ $IFACE != "lo" ]; then
            RECEIVE2=$(($(ip -s -c link show $IFACE | tail -n3 | head -n 1 | awk '{printf $1}') + $RECEIVE2))
        fi
    done
    
    echo -e "$PREFIX$(expr $(expr $RECEIVE2 - $RECEIVE1 ) / 1024)KB/s"
}

get_down_traffic
