#!/bin/bash

# Prints the total ram and used ram in Mb

PREFIX=' '

get_ram()
{
    TOTAL_RAM=$(free -mh | awk  {'print $2'} | head -n 2 | tail -1 | sed -r 's/i//')
    USED_RAM=$(free -mh | awk  {'print $3'} | head -n 2 | tail -1 | sed -r 's/i//')
    MB="MB"

    echo "$PREFIX$USED_RAM/$TOTAL_RAM"
}

get_ram
